### ISSUE TITLE
review

### ISSUE THREAD

**Issue by yevgnenll** [youngwoolee/zumPilot#1]
[restful api 1](https://spoqa.github.io/2012/02/27/rest-introduction.html)

[restful api 2](https://spoqa.github.io/2013/06/11/more-restful-interface.html)

**Comment by youngwoolee** [comment]
감사합니다 참고해서 열심히 보완하겠습니다.

2017. 4. 4. 오후 5:20에 "Park Seung Kwon" <notifications@github.com>님이 작성:

**Comment by yevgnenll** [comment]
이 글은 스포카 라는 국내에서 가장 python을 잘 사용하는 기업이 쓴 글입니다

대한민국에 프로그래밍 천재 변태들만 모아둔 회사라 이곳의 글은 모두 읽어보면 좋을거같습니다
